apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  description: Envoy Gateway (CNCF Envoy project), shared edge proxy
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: edge-proxy
    namespace: envoy-gateway-system
